In [13]:
!pip install -r requirements.txt

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (from -r requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: pyspark in /opt/anaconda3/lib/python3.12/site-packages (from -r requirements.txt (line 2)) (3.5.5)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (from -r requirements.txt (line 3)) (1.26.4)
Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (3.9.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 1)) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: py4j==0.10.9.7 in /opt/anaconda3/lib/python3.12/site-packages (from pyspark->-r requirements.txt (line 2)) (0.10.9.7)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (24.1)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib->-r requirements.txt (line 4)) (3.1.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.16.0)

Exploratory Data Analysis

In [6]:
import pandas as pd
project_data = pd.read_csv('data/projects_data.csv')
project_data.head()

/var/folders/52/1t7m44hx7jj12jd95c57s9q40000gn/T/ipykernel_21061/916278499.py:2: DtypeWarning: Columns (44) have mixed types. Specify dtype option on import or set low_memory=False.
  project_data = pd.read_csv('data/projects_data.csv')

,id,regionname,countryname,prodline,lendinginstr,lendinginstrtype,envassesmentcategorycode,supplementprojectflg,productlinetype,projectstatusdisplay,...,mjtheme3name,mjtheme4name,mjtheme5name,location,GeoLocID,GeoLocName,Latitude,Longitude,Country,Unnamed: 56
0,P162228,Other,World;World,RE,Investment Project Financing,IN,C,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P163962,Africa,Democratic Republic of the Congo;Democratic Re...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,P167672,South Asia,People's Republic of Bangladesh;People's Repub...,PE,Investment Project Financing,IN,NaN,Y,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,P158768,South Asia,Islamic Republic of Afghanistan;Islamic Repu...,PE,Investment Project Financing,IN,A,N,L,Active,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,P161364,Africa,Federal Republic of Nigeria;Federal Republic o...,PE,Investment Project Financing,IN,B,N,L,Active,...,NaN,NaN,NaN,0002327546!$!Ogun State!$!7!$!3.58333!$!NG;000...,0002327546;0002328925;0002565340;0002565343;00...,Ogun State;Niger State;Abia State;Edo;Kebbi St...,7;10;5.41667;6.5;11.5;8,3.58333;6;7.5;6;4;10.5,NG;NG;NG;NG;NG;NG,NaN

In [7]:
project_data.shape

(18248, 57)

In [8]:
project_data.columns

Index(['id', 'regionname', 'countryname', 'prodline', 'lendinginstr',
       'lendinginstrtype', 'envassesmentcategorycode', 'supplementprojectflg',
       'productlinetype', 'projectstatusdisplay', 'status', 'project_name',
       'boardapprovaldate', 'board_approval_month', 'closingdate',
       'lendprojectcost', 'ibrdcommamt', 'idacommamt', 'totalamt', 'grantamt',
       'borrower', 'impagency', 'url', 'projectdoc ', 'majorsector_percent ',
       'sector1', 'sector2', 'sector3', 'sector4', 'sector5', 'sector',
       'mjsector1', 'mjsector2', 'mjsector3', 'mjsector4', 'mjsector5',
       'mjsector', 'theme1', 'theme2', 'theme3', 'theme4', 'theme5', 'theme ',
       'goal', 'financier', 'mjtheme1name', 'mjtheme2name', 'mjtheme3name',
       'mjtheme4name', 'mjtheme5name', 'location', 'GeoLocID', 'GeoLocName',
       'Latitude', 'Longitude', 'Country', 'Unnamed: 56'],
      dtype='object')

In [9]:
project_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18248 entries, 0 to 18247
Data columns (total 57 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        18248 non-null  object
 1   regionname                18248 non-null  object
 2   countryname               18248 non-null  object
 3   prodline                  18248 non-null  object
 4   lendinginstr              18002 non-null  object
 5   lendinginstrtype          18002 non-null  object
 6   envassesmentcategorycode  12437 non-null  object
 7   supplementprojectflg      18195 non-null  object
 8   productlinetype           18248 non-null  object
 9   projectstatusdisplay      18244 non-null  object
 10  status                    18244 non-null  object
 11  project_name              18248 non-null  object
 12  boardapprovaldate         16744 non-null  object
 13  board_approval_month      16744 non-null  object
 14  closingdate               14899 non-null  object
 15  lendprojectcost           18123 non-null  object
 16  ibrdcommamt               18248 non-null  object
 17  idacommamt                18248 non-null  object
 18  totalamt                  18248 non-null  object
 19  grantamt                  18248 non-null  object
 20  borrower                  12329 non-null  object
 21  impagency                 12151 non-null  object
 22  url                       18248 non-null  object
 23  projectdoc                0 non-null      float64
 24  majorsector_percent       0 non-null      float64
 25  sector1                   18248 non-null  object
 26  sector2                   9527 non-null   object
 27  sector3                   6487 non-null   object
 28  sector4                   4376 non-null   object
 29  sector5                   2713 non-null   object
 30  sector                    17610 non-null  object
 31  mjsector1                 0 non-null      float64
 32  mjsector2                 0 non-null      float64
 33  mjsector3                 0 non-null      float64
 34  mjsector4                 0 non-null      float64
 35  mjsector5                 0 non-null      float64
 36  mjsector                  17610 non-null  object
 37  theme1                    18248 non-null  object
 38  theme2                    9853 non-null   object
 39  theme3                    7484 non-null   object
 40  theme4                    5234 non-null   object
 41  theme5                    2928 non-null   object
 42  theme                     0 non-null      float64
 43  goal                      12133 non-null  object
 44  financier                 7060 non-null   object
 45  mjtheme1name              0 non-null      float64
 46  mjtheme2name              0 non-null      float64
 47  mjtheme3name              0 non-null      float64
 48  mjtheme4name              0 non-null      float64
 49  mjtheme5name              0 non-null      float64
 50  location                  4326 non-null   object
 51  GeoLocID                  4326 non-null   object
 52  GeoLocName                4325 non-null   object
 53  Latitude                  4326 non-null   object
 54  Longitude                 4326 non-null   object
 55  Country                   4203 non-null   object
 56  Unnamed: 56               0 non-null      float64
dtypes: float64(14), object(43)
memory usage: 7.9+ MB

In [10]:
project_data.describe()

,projectdoc,majorsector_percent,mjsector1,mjsector2,mjsector3,mjsector4,mjsector5,theme,mjtheme1name,mjtheme2name,mjtheme3name,mjtheme4name,mjtheme5name,Unnamed: 56
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
project_data.drop('Unnamed: 56',inplace=True,axis=1)
project_data.columns

Index(['id', 'regionname', 'countryname', 'prodline', 'lendinginstr',
       'lendinginstrtype', 'envassesmentcategorycode', 'supplementprojectflg',
       'productlinetype', 'projectstatusdisplay', 'status', 'project_name',
       'boardapprovaldate', 'board_approval_month', 'closingdate',
       'lendprojectcost', 'ibrdcommamt', 'idacommamt', 'totalamt', 'grantamt',
       'borrower', 'impagency', 'url', 'projectdoc ', 'majorsector_percent ',
       'sector1', 'sector2', 'sector3', 'sector4', 'sector5', 'sector',
       'mjsector1', 'mjsector2', 'mjsector3', 'mjsector4', 'mjsector5',
       'mjsector', 'theme1', 'theme2', 'theme3', 'theme4', 'theme5', 'theme ',
       'goal', 'financier', 'mjtheme1name', 'mjtheme2name', 'mjtheme3name',
       'mjtheme4name', 'mjtheme5name', 'location', 'GeoLocID', 'GeoLocName',
       'Latitude', 'Longitude', 'Country'],
      dtype='object')

In [12]:
project_data.isnull().sum(axis=0)

id                              0
regionname                      0
countryname                     0
prodline                        0
lendinginstr                  246
lendinginstrtype              246
envassesmentcategorycode     5811
supplementprojectflg           53
productlinetype                 0
projectstatusdisplay            4
status                          4
project_name                    0
boardapprovaldate            1504
board_approval_month         1504
closingdate                  3349
lendprojectcost               125
ibrdcommamt                     0
idacommamt                      0
totalamt                        0
grantamt                        0
borrower                     5919
impagency                    6097
url                             0
projectdoc                  18248
majorsector_percent         18248
sector1                         0
sector2                      8721
sector3                     11761
sector4                     13872
sector5                     15535
sector                        638
mjsector1                   18248
mjsector2                   18248
mjsector3                   18248
mjsector4                   18248
mjsector5                   18248
mjsector                      638
theme1                          0
theme2                       8395
theme3                      10764
theme4                      13014
theme5                      15320
theme                       18248
goal                         6115
financier                   11188
mjtheme1name                18248
mjtheme2name                18248
mjtheme3name                18248
mjtheme4name                18248
mjtheme5name                18248
location                    13922
GeoLocID                    13922
GeoLocName                  13923
Latitude                    13922
Longitude                   13922
Country                     14045
dtype: int64

In [16]:
project_data.describe()

,projectdoc,majorsector_percent,mjsector1,mjsector2,mjsector3,mjsector4,mjsector5,theme,mjtheme1name,mjtheme2name,mjtheme3name,mjtheme4name,mjtheme5name
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

going column wise analysis

In [25]:
project_data['countryname'].unique()

array(['World;World',
       'Democratic Republic of the Congo;Democratic Republic of the Congo',
       "People's Republic of Bangladesh;People's Republic of Bangladesh",
       'Islamic  Republic of Afghanistan;Islamic  Republic of Afghanistan',
       'Federal Republic of Nigeria;Federal Republic of Nigeria',
       'Republic of Tunisia;Republic of Tunisia',
       'Lebanese Republic;Lebanese Republic',
       'Democratic Socialist Republic of Sri Lan;Democratic Socialist Republic of Sri Lan',
       'Nepal;Nepal', 'Kyrgyz Republic;Kyrgyz Republic',
       'Hashemite Kingdom of Jordan;Hashemite Kingdom of Jordan',
       'Republic of the Union of Myanmar;Republic of the Union of Myanmar',
       'Arab Republic of Egypt;Arab Republic of Egypt',
       'United Republic of Tanzania;United Republic of Tanzania',
       'Federal Democratic Republic of Ethiopia;Federal Democratic Republic of Ethiopia',
       'Burkina Faso;Burkina Faso',
       'Republic of Uzbekistan;Republic of Uzbekistan', 'Romania;Romania',
       'Republic of Ghana;Republic of Ghana',
       'Republic of Ecuador;Republic of Ecuador',
       'Socialist Republic of Vietnam;Socialist Republic of Vietnam',
       "People's Republic of China;People's Republic of China",
       'Republic of Senegal;Republic of Senegal', 'Grenada;Grenada',
       'Co-operative Republic of Guyana;Co-operative Republic of Guyana',
       'Central Africa;Central Africa',
       'Republic of Indonesia;Republic of Indonesia',
       'Republic of Kenya;Republic of Kenya',
       'Kingdom of Cambodia;Kingdom of Cambodia',
       'Republic of Angola;Republic of Angola',
       'Republic of India;Republic of India', 'Africa;Africa',
       'Republic of Zambia;Republic of Zambia',
       'Republic of Panama;Republic of Panama',
       'Kingdom of Tonga;Kingdom of Tonga',
       'Islamic Republic of Pakistan;Islamic Republic of Pakistan',
       'Republic of Niger;Republic of Niger',
       'Republic of Uganda;Republic of Uganda',
       'Republic of Madagascar;Republic of Madagascar',
       'Plurinational State of Bolivia;Plurinational State of Bolivia',
       'Kingdom of Morocco;Kingdom of Morocco',
       'Republic of Djibouti;Republic of Djibouti',
       'Somali Democratic Republic;Somali Democratic Republic',
       'Republic of Maldives;Republic of Maldives',
       'Central African Republic;Central African Republic',
       'Western Africa;Western Africa',
       'Republic of Cabo Verde;Republic of Cabo Verde',
       "Republic of Cote d'Ivoire;Republic of Cote d'Ivoire",
       'Montenegro;Montenegro', 'West Bank and Gaza;West Bank and Gaza',
       'Republic of Haiti;Republic of Haiti',
       'Republic of Guinea-Bissau;Republic of Guinea-Bissau',
       'Samoa;Samoa', 'Republic of Congo;Republic of Congo',
       'Federated States of Micronesia;Federated States of Micronesia',
       'Republic of the Marshall Islands;Republic of the Marshall Islands',
       'Republic of Rwanda;Republic of Rwanda',
       'Republic of Albania;Republic of Albania',
       'Republic of Burundi;Republic of Burundi',
       'Argentine Republic;Argentine Republic',
       'Pacific Islands;Pacific Islands',
       'Republic of Turkey;Republic of Turkey',
       'Democratic Republic of Sao Tome and Prin;Democratic Republic of Sao Tome and Prin',
       'Republic of The Gambia;Republic of The Gambia',
       "Lao People's Democratic Republic;Lao People's Democratic Republic",
       'Republic of Liberia;Republic of Liberia',
       'Republic of Benin;Republic of Benin',
       'Republic of Mozambique;Republic of Mozambique',
       'Kingdom of Bhutan;Kingdom of Bhutan',
       'Republic of Cameroon;Republic of Cameroon',
       'Republic of Chad;Republic of Chad',
       'Republic of Guinea;Republic of Guinea',
       'Republic of Yemen;Republic of Yemen',
       'Commonwealth of Dominica;Commonwealth of Dominica',
       'Republic of Palau;Republic of Palau',
       'Republic of Malawi;Republic of Malawi',
       'Republic of Serbia;Republic of Serbia',
       'Republic of Iraq;Republic of Iraq',
       'Republic of the Philippines;Republic of the Philippines',
       'Solomon Islands;Solomon Islands',
       'Republic of Fiji;Republic of Fiji',
       'United Mexican States;United Mexican States',
       'Republic of Colombia;Republic of Colombia',
       'Republic of Peru;Republic of Peru',
       'Republic of Mali;Republic of Mali',
       'Islamic Republic of Mauritania;Islamic Republic of Mauritania',
       'Republic of Nicaragua;Republic of Nicaragua',
       'Republic of Belarus;Republic of Belarus', 'Jamaica;Jamaica',
       'Ukraine;Ukraine', 'Republic of Togo;Republic of Togo',
       'Republic of Guatemala;Republic of Guatemala',
       'Republic of Sierra Leone;Republic of Sierra Leone',
       'Republic of Moldova;Republic of Moldova',
       'Republic of Armenia;Republic of Armenia',
       'Republic of Costa Rica;Republic of Costa Rica',
       'Republic of Tajikistan;Republic of Tajikistan',
       'Latin America;Latin America',
       'Federative Republic of Brazil;Federative Republic of Brazil',
       'Bosnia and Herzegovina;Bosnia and Herzegovina',
       'Republic of Suriname;Republic of Suriname', 'Mongolia;Mongolia',
       'Oriental Republic of Uruguay;Oriental Republic of Uruguay',
       'Republic of Kiribati;Republic of Kiribati',
       'Kingdom of Lesotho;Kingdom of Lesotho', 'Tuvalu;Tuvalu',
       'Southern Africa;Southern Africa', 'Georgia;Georgia',
       'Gabonese Republic;Gabonese Republic',
       'Republic of Chile;Republic of Chile',
       'Republic of Kosovo;Republic of Kosovo',
       'Dominican Republic;Dominican Republic',
       'Organization of Eastern Caribbean States;Organization of Eastern Caribbean States',
       'Caribbean;Caribbean', 'Republic of Zimbabwe;Republic of Zimbabwe',
       'Republic of Mauritius;Republic of Mauritius',
       'The Independent State of Papua New Guine;The Independent State of Papua New Guine',
       'Republic of Vanuatu;Republic of Vanuatu',
       'Eastern Africa;Eastern Africa',
       'St. Vincent and the Grenadines;St. Vincent and the Grenadines',
       'Republic of Honduras;Republic of Honduras',
       'Republic of South Sudan;Republic of South Sudan',
       'Republic of Croatia;Republic of Croatia',
       'Democratic Republic of Timor-Leste;Democratic Republic of Timor-Leste',
       'Republic of South Africa;Republic of South Africa',
       'Republic of Botswana;Republic of Botswana',
       'Republic of Kazakhstan;Republic of Kazakhstan',
       'Republic of Azerbaijan;Republic of Azerbaijan',
       'Kingdom of Swaziland;Kingdom of Swaziland',
       'Union of the Comoros;Union of the Comoros',
       'Turkmenistan;Turkmenistan',
       'Europe and Central Asia;Europe and Central Asia',
       'South Asia;South Asia',
       'Macedonia; former Yugoslav Republic of;Macedonia; former Yugoslav Republic of',
       'St. Lucia;St. Lucia', 'Belize;Belize',
       'Republic of Namibia;Republic of Namibia',
       'Republic of the Sudan;Republic of the Sudan',
       'Republic of Paraguay;Republic of Paraguay',
       'Western Balkans;Western Balkans',
       'East Asia and Pacific;East Asia and Pacific',
       'Republic of Bulgaria;Republic of Bulgaria',
       'Central Asia;Central Asia',
       'Republic of Seychelles;Republic of Seychelles',
       'Kingdom of Thailand;Kingdom of Thailand',
       'Republic of Poland;Republic of Poland',
       'Multi-Regional;Multi-Regional',
       'Republic of El Salvador;Republic of El Salvador',
       'Caucasus;Caucasus', 'Russian Federation;Russian Federation',
       'Middle East and North Africa;Middle East and North Africa',
       'Antigua and Barbuda;Antigua and Barbuda',
       'Central America;Central America',
       'Commonwealth of The Bahamas;Commonwealth of The Bahamas',
       'Republic of Trinidad and Tobago;Republic of Trinidad and Tobago',
       "Socialist People's Libyan Arab Jamahiriy;Socialist People's Libyan Arab Jamahiriy",
       'Czech Republic;Czech Republic',
       'Republic of Latvia;Republic of Latvia', 'Mekong;Mekong',
       'American Samoa;American Samoa',
       'Syrian Arab Republic;Syrian Arab Republic', 'Asia;Asia',
       'Andean Countries;Andean Countries', 'Hungary;Hungary',
       'Republic of Equatorial Guinea;Republic of Equatorial Guinea',
       "People's Democratic Republic of Algeria;People's Democratic Republic of Algeria",
       'Barbados;Barbados', 'Malaysia;Malaysia',
       'State of Eritrea;State of Eritrea', 'Mercosur;Mercosur',
       'Slovak Republic;Slovak Republic',
       'Republica Bolivariana de Venezuela;Republica Bolivariana de Venezuela',
       'Islamic Republic of Iran;Islamic Republic of Iran',
       'Republic of Lithuania;Republic of Lithuania',
       'St. Kitts and Nevis;St. Kitts and Nevis',
       'Republic of Korea;Republic of Korea',
       'Republic of Slovenia;Republic of Slovenia',
       'Republic of Estonia;Republic of Estonia',
       'Red Sea and Gulf of Aden;Red Sea and Gulf of Aden',
       'Aral Sea;Aral Sea', 'Republic of Cyprus;Republic of Cyprus',
       'Socialist Federal Republic of Yugoslavia;Socialist Federal Republic of Yugoslavia',
       'Portuguese Republic;Portuguese Republic',
       'Sultanate of Oman;Sultanate of Oman',
       'Hellenic Republic;Hellenic Republic',
       'Kingdom of Spain;Kingdom of Spain', 'Ireland;Ireland',
       'Republic of Singapore;Republic of Singapore',
       'State of Israel;State of Israel',
       'Republic of Finland;Republic of Finland',
       'Republic of Iceland;Republic of Iceland',
       'New Zealand;New Zealand', 'Taiwan; China;Taiwan; China',
       'EU Accession Countries;EU Accession Countries',
       'Sint Maarten;Sint Maarten', 'Japan;Japan',
       'Italian Republic;Italian Republic',
       'Kingdom of Norway;Kingdom of Norway',
       'Republic of Malta;Republic of Malta',
       'Kingdom of Denmark;Kingdom of Denmark',
       'Republic of Austria;Republic of Austria',
       'Commonwealth of Australia;Commonwealth of Australia',
       'Kingdom of Belgium;Kingdom of Belgium',
       'Kingdom of the Netherlands;Kingdom of the Netherlands',
       'Grand Duchy of Luxembourg;Grand Duchy of Luxembourg',
       'French Republic;French Republic'], dtype=object)

In [28]:
project_data['offical_country_name'] = project_data['countryname'].str.split(';').str.get(0)
project_data['offical_country_name'].unique()

array(['World', 'Democratic Republic of the Congo',
       "People's Republic of Bangladesh",
       'Islamic  Republic of Afghanistan', 'Federal Republic of Nigeria',
       'Republic of Tunisia', 'Lebanese Republic',
       'Democratic Socialist Republic of Sri Lan', 'Nepal',
       'Kyrgyz Republic', 'Hashemite Kingdom of Jordan',
       'Republic of the Union of Myanmar', 'Arab Republic of Egypt',
       'United Republic of Tanzania',
       'Federal Democratic Republic of Ethiopia', 'Burkina Faso',
       'Republic of Uzbekistan', 'Romania', 'Republic of Ghana',
       'Republic of Ecuador', 'Socialist Republic of Vietnam',
       "People's Republic of China", 'Republic of Senegal', 'Grenada',
       'Co-operative Republic of Guyana', 'Central Africa',
       'Republic of Indonesia', 'Republic of Kenya',
       'Kingdom of Cambodia', 'Republic of Angola', 'Republic of India',
       'Africa', 'Republic of Zambia', 'Republic of Panama',
       'Kingdom of Tonga', 'Islamic Republic of Pakistan',
       'Republic of Niger', 'Republic of Uganda',
       'Republic of Madagascar', 'Plurinational State of Bolivia',
       'Kingdom of Morocco', 'Republic of Djibouti',
       'Somali Democratic Republic', 'Republic of Maldives',
       'Central African Republic', 'Western Africa',
       'Republic of Cabo Verde', "Republic of Cote d'Ivoire",
       'Montenegro', 'West Bank and Gaza', 'Republic of Haiti',
       'Republic of Guinea-Bissau', 'Samoa', 'Republic of Congo',
       'Federated States of Micronesia',
       'Republic of the Marshall Islands', 'Republic of Rwanda',
       'Republic of Albania', 'Republic of Burundi', 'Argentine Republic',
       'Pacific Islands', 'Republic of Turkey',
       'Democratic Republic of Sao Tome and Prin',
       'Republic of The Gambia', "Lao People's Democratic Republic",
       'Republic of Liberia', 'Republic of Benin',
       'Republic of Mozambique', 'Kingdom of Bhutan',
       'Republic of Cameroon', 'Republic of Chad', 'Republic of Guinea',
       'Republic of Yemen', 'Commonwealth of Dominica',
       'Republic of Palau', 'Republic of Malawi', 'Republic of Serbia',
       'Republic of Iraq', 'Republic of the Philippines',
       'Solomon Islands', 'Republic of Fiji', 'United Mexican States',
       'Republic of Colombia', 'Republic of Peru', 'Republic of Mali',
       'Islamic Republic of Mauritania', 'Republic of Nicaragua',
       'Republic of Belarus', 'Jamaica', 'Ukraine', 'Republic of Togo',
       'Republic of Guatemala', 'Republic of Sierra Leone',
       'Republic of Moldova', 'Republic of Armenia',
       'Republic of Costa Rica', 'Republic of Tajikistan',
       'Latin America', 'Federative Republic of Brazil',
       'Bosnia and Herzegovina', 'Republic of Suriname', 'Mongolia',
       'Oriental Republic of Uruguay', 'Republic of Kiribati',
       'Kingdom of Lesotho', 'Tuvalu', 'Southern Africa', 'Georgia',
       'Gabonese Republic', 'Republic of Chile', 'Republic of Kosovo',
       'Dominican Republic', 'Organization of Eastern Caribbean States',
       'Caribbean', 'Republic of Zimbabwe', 'Republic of Mauritius',
       'The Independent State of Papua New Guine', 'Republic of Vanuatu',
       'Eastern Africa', 'St. Vincent and the Grenadines',
       'Republic of Honduras', 'Republic of South Sudan',
       'Republic of Croatia', 'Democratic Republic of Timor-Leste',
       'Republic of South Africa', 'Republic of Botswana',
       'Republic of Kazakhstan', 'Republic of Azerbaijan',
       'Kingdom of Swaziland', 'Union of the Comoros', 'Turkmenistan',
       'Europe and Central Asia', 'South Asia', 'Macedonia', 'St. Lucia',
       'Belize', 'Republic of Namibia', 'Republic of the Sudan',
       'Republic of Paraguay', 'Western Balkans', 'East Asia and Pacific',
       'Republic of Bulgaria', 'Central Asia', 'Republic of Seychelles',
       'Kingdom of Thailand', 'Republic of Poland', 'Multi-Regional',
       'Republic of El Salvador', 'Caucasus', 'Russian Federation',
       'Middle East and North Africa', 'Antigua and Barbuda',
       'Central America', 'Commonwealth of The Bahamas',
       'Republic of Trinidad and Tobago',
       "Socialist People's Libyan Arab Jamahiriy", 'Czech Republic',
       'Republic of Latvia', 'Mekong', 'American Samoa',
       'Syrian Arab Republic', 'Asia', 'Andean Countries', 'Hungary',
       'Republic of Equatorial Guinea',
       "People's Democratic Republic of Algeria", 'Barbados', 'Malaysia',
       'State of Eritrea', 'Mercosur', 'Slovak Republic',
       'Republica Bolivariana de Venezuela', 'Islamic Republic of Iran',
       'Republic of Lithuania', 'St. Kitts and Nevis',
       'Republic of Korea', 'Republic of Slovenia', 'Republic of Estonia',
       'Red Sea and Gulf of Aden', 'Aral Sea', 'Republic of Cyprus',
       'Socialist Federal Republic of Yugoslavia', 'Portuguese Republic',
       'Sultanate of Oman', 'Hellenic Republic', 'Kingdom of Spain',
       'Ireland', 'Republic of Singapore', 'State of Israel',
       'Republic of Finland', 'Republic of Iceland', 'New Zealand',
       'Taiwan', 'EU Accession Countries', 'Sint Maarten', 'Japan',
       'Italian Republic', 'Kingdom of Norway', 'Republic of Malta',
       'Kingdom of Denmark', 'Republic of Austria',
       'Commonwealth of Australia', 'Kingdom of Belgium',
       'Kingdom of the Netherlands', 'Grand Duchy of Luxembourg',
       'French Republic'], dtype=object)